"""add shap_cache table

Revision ID: 1e22c8aa8775
Revises: 4b1cc288c9c5
Create Date: 2026-04-01 16:17:33.267680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e22c8aa8775'
down_revision: Union[str, None] = '4b1cc288c9c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shap_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('genome_id', sa.UUID(), nullable=False),
    sa.Column('split_id', sa.UUID(), nullable=False),
    sa.Column('annotation_id', sa.String(length=255), nullable=True),
    sa.Column('split_choice', sa.String(length=10), nullable=False),
    sa.Column('max_samples', sa.Integer(), nullable=False),
    sa.Column('operations_count', sa.Integer(), nullable=False),
    sa.Column('feature_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('mean_abs_shap', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('base_value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['genome_id'], ['genomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['split_id'], ['dataset_splits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shap_cache_lookup', 'shap_cache', ['genome_id', 'split_id', 'annotation_id', 'split_choice', 'max_samples'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_shap_cache_lookup', table_name='shap_cache')
    op.drop_table('shap_cache')
    # ### end Alembic commands ###
