"""Add x_data and y_data columns to datasets

Revision ID: 4b1cc288c9c5
Revises: a8b9c0d1e2f3
Create Date: 2026-02-15 11:58:59.528001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1cc288c9c5'
down_revision: Union[str, None] = 'a8b9c0d1e2f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('x_data', sa.LargeBinary(), nullable=True))
    op.add_column('datasets', sa.Column('y_data', sa.LargeBinary(), nullable=True))
    op.drop_index(op.f('idx_experiments_dataset_id'), table_name='experiments')
    op.create_index(op.f('ix_explanations_genome_id'), 'explanations', ['genome_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_explanations_genome_id'), table_name='explanations')
    op.create_index(op.f('idx_experiments_dataset_id'), 'experiments', ['dataset_id'], unique=False)
    op.drop_column('datasets', 'y_data')
    op.drop_column('datasets', 'x_data')
    # ### end Alembic commands ###
