"""Add gene_origins table for innovation tracking

Revision ID: dbf82e8c2095
Revises: 3f302fe63174
Create Date: 2025-10-09 10:21:26.890620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbf82e8c2095'
down_revision: Union[str, None] = '3f302fe63174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gene_origins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('innovation_number', sa.Integer(), nullable=False),
    sa.Column('gene_type', sa.String(length=20), nullable=False),
    sa.Column('origin_genome_id', sa.UUID(), nullable=False),
    sa.Column('origin_generation', sa.Integer(), nullable=False),
    sa.Column('connection_from', sa.Integer(), nullable=True),
    sa.Column('connection_to', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.Integer(), nullable=True),
    sa.Column('initial_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origin_genome_id'], ['genomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('innovation_number', 'gene_type', 'experiment_id', name='uq_innovation_type_experiment')
    )
    op.create_index('idx_gene_origin_generation', 'gene_origins', ['origin_generation'], unique=False)
    op.create_index('idx_gene_origin_type', 'gene_origins', ['gene_type', 'innovation_number'], unique=False)
    op.create_index(op.f('ix_gene_origins_innovation_number'), 'gene_origins', ['innovation_number'], unique=False)
    op.create_index(op.f('ix_gene_origins_origin_generation'), 'gene_origins', ['origin_generation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_origins_origin_generation'), table_name='gene_origins')
    op.drop_index(op.f('ix_gene_origins_innovation_number'), table_name='gene_origins')
    op.drop_index('idx_gene_origin_type', table_name='gene_origins')
    op.drop_index('idx_gene_origin_generation', table_name='gene_origins')
    op.drop_table('gene_origins')
    # ### end Alembic commands ###
