"""add config to model

Revision ID: 3c7a9e11a91a
Revises: 
Create Date: 2024-11-20 21:08:56.416239

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c7a9e11a91a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neat_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', postgresql.JSON(astext_type=Text()), nullable=False))
        batch_op.alter_column('version',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('parsed_model',
               existing_type=sa.TEXT(),
               type_=postgresql.JSON(astext_type=Text()),
               existing_nullable=False)
        batch_op.alter_column('raw_data',
               existing_type=sa.BLOB(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('neat_model', schema=None) as batch_op:
        batch_op.alter_column('raw_data',
               existing_type=sa.Text(),
               type_=sa.BLOB(),
               existing_nullable=False)
        batch_op.alter_column('parsed_model',
               existing_type=postgresql.JSON(astext_type=Text()),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('version',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('config')

    # ### end Alembic commands ###
