"""add split size

Revision ID: 71e087758e10
Revises: 6e5253aa850f
Create Date: 2025-04-27 16:01:48.708069

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71e087758e10"
down_revision = "6e5253aa850f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_split", schema=None) as batch_op:
        batch_op.add_column(sa.Column("split_size", sa.Float()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset_split", schema=None) as batch_op:
        batch_op.drop_column("split_size")

    # ### end Alembic commands ###
